### ISSUE TITLE
invalid rc2 transaction format, invalid Field:signature, RLP

### ISSUE THREAD

**Issue by wjoj** [WeBankFinTech/WeIdentity-Rest-Service#79]
####request url:http://127.0.0.1:6001/weid/api/encode| type:POST| method:[HttpResponseData com.webank.weid.http.service.impl.TransactionServiceImpl.encodeTransaction(String)]| args:[{"functionArg":{"publicKey":"2790745665788174420359037113479980331716268332496566895530889185796569443759490118427272104796664243892252663395654970119725027074813233023052697492528383"},"functionName":"createWeId","transactionArg": {"nonce": "9033578762736606715"},"v":"1.0.0"}]
2023-04-17 02:52:58.316 [http-nio-6001-exec-1] INFO  ServiceLogAspect() - ####response method:[HttpResponseData com.webank.weid.http.service.impl.TransactionServiceImpl.encodeTransaction(String)]| args:[{"functionArg":{"publicKey":"2790745665788174420359037113479980331716268332496566895530889185796569443759490118427272104796664243892252663395654970119725027074813233023052697492528383"},"functionName":"createWeId","transactionArg": {"nonce": "9033578762736606715"},"v":"1.0.0"}]| result:{
  "errorCode" : 0,
  "errorMessage" : "success",
  "loopback" : null,
  "respBody" : {
    "blockLimit" : "1327",
    "data" : "0x635ef5a50000000000000000000000005619fc95bb3e255ef7d6ec456ace2e37023c986f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000d313638313639393937383231330000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016d6469643a776569643a313a307835363139666339356262336532353565663764366563343536616365326533373032336339383666236b6579732d37323762643536662c45643235353139566572696669636174696f6e4b6579323032302c6469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662c7a357272663371506669515875633437554151556f6f4c506e4a7565586e61354e55786147735264367750743462324747687366446679644d733836317444354761643154346532326b7437797664516557436e6f647577695751416b6d59766a3642716a726e76424650416a64614753627058354e7641336d4b47446f594d4b5a484c6f643557563846396973426d635556784c7067467952616161556e344e393450367645797a476a784c6a6f5946594a3171415a564731595a71684b34773650706b6d4a444271647768507855786a6b4339445761000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000786469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662330346238643861652c57654964656e746974792c68747470733a2f2f6769746875622e636f6d2f576542616e6b426c6f636b636861696e2f57654964656e746974790000000000000000",
    "encodedTransaction" : "+QO4iH1duAXTbZ37hRdIduf/hRdIduf/ggUvlBIhqIvMnRh+rr/ltIdSmP3+kcDRgLkDhGNe9aUAAAAAAAAAAAAAAABWGfyVuz4lXvfW7EVqzi43AjyYbwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANMTY4MTY5OTk3ODIxMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW1kaWQ6d2VpZDoxOjB4NTYxOWZjOTViYjNlMjU1ZWY3ZDZlYzQ1NmFjZTJlMzcwMjNjOTg2ZiNrZXlzLTcyN2JkNTZmLEVkMjU1MTlWZXJpZmljYXRpb25LZXkyMDIwLGRpZDp3ZWlkOjE6MHg1NjE5ZmM5NWJiM2UyNTVlZjdkNmVjNDU2YWNlMmUzNzAyM2M5ODZmLHo1cnJmM3FQZmlRWHVjNDdVQVFVb29MUG5KdWVYbmE1TlV4YUdzUmQ2d1B0NGIyR0doc2ZEZnlkTXM4NjF0RDVHYWQxVDRlMjJrdDd5dmRRZVdDbm9kdXdpV1FBa21Zdmo2QnFqcm52QkZQQWpkYUdTYnBYNU52QTNtS0dEb1lNS1pITG9kNVdWOEY5aXNCbWNVVnhMcGdGeVJhYWFVbjROOTRQNnZFeXpHanhMam9ZRllKMXFBWlZHMVlacWhLNHc2UHBrbUpEQnFkd2hQeFV4amtDOURXYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHhkaWQ6d2VpZDoxOjB4NTYxOWZjOTViYjNlMjU1ZWY3ZDZlYzQ1NmFjZTJlMzcwMjNjOTg2ZiMwNGI4ZDhhZSxXZUlkZW50aXR5LGh0dHBzOi8vZ2l0aHViLmNvbS9XZUJhbmtCbG9ja2NoYWluL1dlSWRlbnRpdHkAAAAAAAAAAAEBgA=="
  }
}| cost tims:483ms
2023-04-17 02:52:58.407 [http-nio-6001-exec-3] INFO  ServiceLogAspect() - ####request url:http://127.0.0.1:6001/weid/api/transact| type:POST| method:[HttpResponseData com.webank.weid.http.service.impl.TransactionServiceImpl.sendTransaction(String)]| args:[{"functionArg":{},"functionName":"createWeId","transactionArg": {"nonce": "9033578762736606715","data": "0x635ef5a50000000000000000000000005619fc95bb3e255ef7d6ec456ace2e37023c986f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000d313638313639393937383231330000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016d6469643a776569643a313a307835363139666339356262336532353565663764366563343536616365326533373032336339383666236b6579732d37323762643536662c45643235353139566572696669636174696f6e4b6579323032302c6469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662c7a357272663371506669515875633437554151556f6f4c506e4a7565586e61354e55786147735264367750743462324747687366446679644d733836317444354761643154346532326b7437797664516557436e6f647577695751416b6d59766a3642716a726e76424650416a64614753627058354e7641336d4b47446f594d4b5a484c6f643557563846396973426d635556784c7067467952616161556e344e393450367645797a476a784c6a6f5946594a3171415a564731595a71684b34773650706b6d4a444271647768507855786a6b4339445761000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000786469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662330346238643861652c57654964656e746974792c68747470733a2f2f6769746875622e636f6d2f576542616e6b426c6f636b636861696e2f57654964656e746974790000000000000000","signedMessage": "T0OHQUiak8oX9S4ehLEwyFdS0C4S+G1/dzNfNyLy3pwMsh8XIalb9KBAitlc5oZ9NqoXxWIq6pBl8JLOJxvomAA=","blockLimit": "1327","signType": "1"},"v":"1.0.0"}]
2023-04-17 02:52:58.426 [http-nio-6001-exec-3] ERROR JsonRpcService() - parseResponseIntoJsonRpcResponse failed for non-empty error message, method: sendRawTransaction, group: 1, seq: 13dced0145104c27ab143b6910e5be50, retErrorMessage: INTERNAL_ERROR: : INTERNAL_ERROR: : /Users/runner/work/FISCO-BCOS/FISCO-BCOS/libdevcore/RLP.cpp(136): Throw in function void dev::RLP::requireGood() const
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadRLP>
std::exception::what: std::exception
[dev::eth::tag_field*] = invalid rc2 transaction format, invalid Field:signature, RLP: f903b8887d5db805d36d9dfb85174876e7ff85174876e7ff82052f941221a88bcc9d187eaebfe5b4875298fdfe91c0d180b90384635ef5a50000000000000000000000005619fc95bb3e255ef7d6ec456ace2e37023c986f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000d313638313639393937383231330000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016d6469643a776569643a313a307835363139666339356262336532353565663764366563343536616365326533373032336339383666236b6579732d37323762643536662c45643235353139566572696669636174696f6e4b6579323032302c6469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662c7a357272663371506669515875633437554151556f6f4c506e4a7565586e61354e55786147735264367750743462324747687366446679644d733836317444354761643154346532326b7437797664516557436e6f647577695751416b6d59766a3642716a726e76424650416a64614753627058354e7641336d4b47446f594d4b5a484c6f643557563846396973426d635556784c7067467952616161556e344e393450367645797a476a784c6a6f5946594a3171415a564731595a71684b34773650706b6d4a444271647768507855786a6b4339445761000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000786469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662330346238643861652c57654964656e746974792c68747470733a2f2f6769746875622e636f6d2f576542616e6b426c6f636b636861696e2f57654964656e746974790000000000000000010180
, retErrorCode: -32603
2023-04-17 02:52:58.428 [http-nio-6001-exec-3] ERROR RawTransactionServiceEngineV2() - [createWeId] create failed due to unknown transaction error. 
org.fisco.bcos.sdk.client.exceptions.ClientException: parseResponseIntoJsonRpcResponse failed for non-empty error message, method: sendRawTransaction ,group: 1 ,seq:13dced0145104c27ab143b6910e5be50,retErrorMessage: INTERNAL_ERROR: : INTERNAL_ERROR: : /Users/runner/work/FISCO-BCOS/FISCO-BCOS/libdevcore/RLP.cpp(136): Throw in function void dev::RLP::requireGood() const
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadRLP>
std::exception::what: std::exception
[dev::eth::tag_field*] = invalid rc2 transaction format, invalid Field:signature, RLP: f903b8887d5db805d36d9dfb85174876e7ff85174876e7ff82052f941221a88bcc9d187eaebfe5b4875298fdfe91c0d180b90384635ef5a50000000000000000000000005619fc95bb3e255ef7d6ec456ace2e37023c986f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000000000000000000d313638313639393937383231330000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000016d6469643a776569643a313a307835363139666339356262336532353565663764366563343536616365326533373032336339383666236b6579732d37323762643536662c45643235353139566572696669636174696f6e4b6579323032302c6469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662c7a357272663371506669515875633437554151556f6f4c506e4a7565586e61354e55786147735264367750743462324747687366446679644d733836317444354761643154346532326b7437797664516557436e6f647577695751416b6d59766a3642716a726e76424650416a64614753627058354e7641336d4b47446f594d4b5a484c6f643557563846396973426d635556784c7067467952616161556e344e393450367645797a476a784c6a6f5946594a3171415a564731595a71684b34773650706b6d4a444271647768507855786a6b4339445761000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000786469643a776569643a313a3078353631396663393562623365323535656637643665633435366163653265333730323363393836662330346238643861652c57654964656e746974792c68747470733a2f2f6769746875622e636f6d2f576542616e6b426c6f636b636861696e2f57654964656e746974790000000000000000010180

	at org.fisco.bcos.sdk.client.JsonRpcService.parseResponseIntoJsonRpcResponse(JsonRpcService.java:214) ~[fisco-bcos-java-sdk-2.9.1.jar:?]
	at org.fisco.bcos.sdk.client.JsonRpcService.sendRequestToGroup(JsonRpcService.java:87) ~[fisco-bcos-java-sdk-2.9.1.jar:?]
	at org.fisco.bcos.sdk.client.JsonRpcService.sendRequestToGroup(JsonRpcService.java:65) ~[fisco-bcos-java-sdk-2.9.1.jar:?]
	at org.fisco.bcos.sdk.client.ClientImpl.sendRawTransaction(ClientImpl.java:129) ~[fisco-bcos-java-sdk-2.9.1.jar:?]
	at com.webank.weid.service.impl.engine.fiscov2.RawTransactionServiceEngineV2.sendTransaction(RawTransactionServiceEngineV2.java:90) ~[weid-java-sdk-1.8.6-rc.3-SNAPSHOT.jar:?]
	at com.webank.weid.service.impl.engine.fiscov2.RawTransactionServiceEngineV2.createWeId(RawTransactionServiceEngineV2.java:198)

**Comment by vladilen11** [comment]
I have same question.https://github.com/WeBankBlockchain/WeIdentity-Rest-Service/issues/80

**Comment by youwenbusi** [comment]
最新的代码（develop分支）已解决这个bug，将会合并到3.1.1发布
